(() => {
  const config = window.PRESENTATION_DRAFT;
  const names = document.getElementById('name-dialog');
  const coverDialog = document.getElementById('cover-dialog');
  const promptField = document.getElementById('build-prompt');
  const feedback = document.getElementById('copy-feedback');
  let toastTimer;
  function notify(message) {const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),3000);}
  function applyName(value, announce=false) {
    const name=String(value).trim().replace(/\s+/g,' ').slice(0,30);if(!name)return;
    document.querySelectorAll('[data-product-name]').forEach(el=>el.textContent=name);
    document.querySelector('.wordmark').setAttribute('aria-label',name+' — voltar ao início');
    document.title=name+' — by julio andrade';
    promptField.value=config.promptTemplate.replaceAll('{{name}}',name);feedback.textContent='';
    document.querySelectorAll('[data-name-choice]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.nameChoice===name)));
    try{localStorage.setItem('presentation-draft-name',name);}catch{}
    if(announce){names.close();notify('Nome em teste: '+name);}
  }
  for(const item of config.names){const b=document.createElement('button');b.type='button';b.dataset.nameChoice=item.name;const title=document.createElement('b');title.textContent=item.name;const text=document.createElement('span');text.textContent=item.direction;b.append(title,text);b.addEventListener('click',()=>applyName(item.name,true));document.getElementById('name-options').append(b);}
  applyName(config.defaultName);
  document.querySelectorAll('[data-open-names]').forEach(b=>b.addEventListener('click',()=>names.showModal()));
  document.getElementById('close-names').addEventListener('click',()=>names.close());
  document.getElementById('custom-name-form').addEventListener('submit',e=>{e.preventDefault();applyName(new FormData(e.target).get('name'),true);});
  document.getElementById('close-cover').addEventListener('click',()=>coverDialog.close());
  [names,coverDialog].forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}}));
  document.getElementById('copy-prompt').addEventListener('click',async()=>{
    let copied=false;
    try{await navigator.clipboard.writeText(promptField.value);copied=true;}catch{
      promptField.focus();promptField.select();
      try{copied=document.execCommand('copy');}catch{}
    }
    if(copied){feedback.textContent='Prompt de instalação copiado.';notify('Prompt de instalação copiado.');}
    else{promptField.focus();promptField.select();feedback.textContent='Texto selecionado. Use o comando Copiar do seu dispositivo.';}
  });
  document.getElementById('expand-prompt').addEventListener('click',e=>{const expanded=promptField.classList.toggle('expanded');e.currentTarget.setAttribute('aria-expanded',String(expanded));e.currentTarget.innerHTML=expanded?'Recolher prompt <span>−</span>':'Ler prompt completo <span>+</span>';});
  document.getElementById('toggle-motion').addEventListener('click',e=>{const paused=document.body.classList.toggle('motion-paused');e.currentTarget.setAttribute('aria-pressed',String(paused));e.currentTarget.setAttribute('aria-label',paused?'Retomar animações':'Pausar animações');e.currentTarget.title=paused?'Retomar animações':'Pausar animações';e.currentTarget.textContent=paused?'▷':'Ⅱ';});
  function wireTabs(tabs,activate){tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%tabs.length;if(e.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();activate(tabs[next]);tabs[next].focus();}});});}
  const tabs=[...document.querySelectorAll('[data-tab]')];
  function activateTab(tab){tabs.forEach(b=>{const selected=b===tab;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;document.getElementById('panel-'+b.dataset.tab).hidden=!selected;});const overview=tab.dataset.tab==='overview';document.getElementById('demo-period').hidden=!overview;document.querySelector('label[for="demo-period"]').hidden=!overview;}
  wireTabs(tabs,activateTab);document.querySelectorAll('[data-switch]').forEach(b=>b.addEventListener('click',()=>{const tab=tabs.find(t=>t.dataset.tab===b.dataset.switch);activateTab(tab);tab.focus();}));
  const periods={30:{posts:'48',views:'128,4 mil',comments:'1.260',ideas:'12',reels:'24',carousels:'18',static:'6',points:'M0 110 50 94 100 113 150 70 200 85 250 53 300 72 350 40 400 56 450 24 500 49 550 32 600 10',mix:'var(--teal) 0 50%,#6aacb4 50% 87.5%,#c2d9df 87.5% 100%',label:'Exemplo: 24 Reels, 18 carrosséis e 6 posts'},7:{posts:'14',views:'32,8 mil',comments:'342',ideas:'4',reels:'7',carousels:'5',static:'2',points:'M0 125 100 95 200 106 300 71 400 91 500 59 600 77',mix:'var(--teal) 0 50%,#6aacb4 50% 85.7%,#c2d9df 85.7% 100%',label:'Exemplo: 7 Reels, 5 carrosséis e 2 posts'}};
  document.getElementById('demo-period').addEventListener('change',e=>{const data=periods[e.target.value];document.querySelectorAll('[data-kpi]').forEach(el=>el.textContent=data[el.dataset.kpi]);document.querySelectorAll('[data-format]').forEach(el=>el.textContent=data[el.dataset.format]);document.getElementById('chart-line').setAttribute('d',data.points);document.getElementById('chart-area').setAttribute('d',data.points+'V150H0Z');document.querySelector('.donut').style.background='conic-gradient('+data.mix+')';document.querySelector('.donut').setAttribute('aria-label',data.label);});
  const posts=[{id:'study',file:'DdHyK0DlNbu.jpg',title:'Apresentações com IA: meu processo',topic:'IA NA PRÁTICA',views:12400,comments:284,conversation:64,interest:86,tag:'Um tutorial para revisitar'},{id:'routine',file:'DdKii02FHEQ.jpg',title:'O que a rotina médica tira de você',topic:'ROTINA MÉDICA',views:18600,comments:196,conversation:83,interest:71,tag:'Uma conversa para continuar'},{id:'story',file:'DHb7THEhtn6.jpg',title:'Minha história em números',topic:'TRAJETÓRIA',views:9200,comments:118,conversation:49,interest:65,tag:'Um novo ângulo para contar'}];
  const fold=text=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function renderPosts(){const search=fold(document.getElementById('content-search').value);const sort=document.getElementById('content-sort').value;const visible=posts.filter(p=>fold(p.title+' '+p.topic).includes(search)).sort((a,b)=>b[sort]-a[sort]);document.getElementById('content-cards').innerHTML=visible.map(p=>`<article class="content-card"><button class="cover-button" type="button" data-cover="${p.id}" aria-label="Ampliar capa: ${p.title}"><img src="assets/${p.file}" alt="Capa de ${p.title}" loading="lazy"><span aria-hidden="true">↗</span></button><div class="card-copy"><small>${p.topic}</small><h3>${p.title}</h3><div class="post-numbers"><div><span>Visualizações</span><b>${(p.views/1000).toLocaleString('pt-BR')} mil</b></div><div><span>Comentários</span><b>${p.comments}</b></div></div><div class="post-track"><span>Conversa</span><div aria-hidden="true"><i style="width:${p.conversation}%"></i></div></div><div class="post-track"><span>Interesse</span><div aria-hidden="true"><i style="width:${p.interest}%"></i></div></div><span class="card-tag">${p.tag}</span></div></article>`).join('');document.getElementById('no-content').hidden=visible.length>0;}
  document.getElementById('content-search').addEventListener('input',renderPosts);document.getElementById('content-sort').addEventListener('change',renderPosts);renderPosts();
  document.getElementById('content-cards').addEventListener('click',e=>{const button=e.target.closest('[data-cover]');if(!button)return;const p=posts.find(p=>p.id===button.dataset.cover);const img=document.getElementById('cover-image');img.src='assets/'+p.file;img.alt='Capa original: '+p.title;document.getElementById('cover-title').textContent=p.title;coverDialog.showModal();});
  const icon=id=>`<svg class="icon" aria-hidden="true"><use href="#i-${id}"/></svg>`;
  const stages={profile:{title:'Seu contexto vem primeiro.',text:'Perfil, público e identidade visual. A montagem começa por você.',tags:['Seu perfil','Seus objetivos','Sua identidade'],art:`<div class="profile-preview"><div><span class="avatar">${icon('user')}</span><div><b>Seu perfil profissional</b><p>Conteúdo com a sua identidade</p></div></div><div class="profile-lines"><span></span><span></span><span></span></div><div class="swatches"><i></i><i></i><i></i><i></i><span>Sua paleta. Seu estilo.</span></div></div>`},organize:{title:'Cada coisa no seu lugar.',text:'A skill orienta a organização dos arquivos, das fontes e do histórico disponível.',tags:['Instruções','Código','Fontes autorizadas'],art:`<div class="files-preview"><div>${icon('spark')}Skill<span>instruções</span></div><div>${icon('grid')}Aplicativo<span>código</span></div><div>${icon('bookmark')}Seu histórico<span>fontes</span></div></div>`},create:{title:'O painel ganha forma.',text:'A IA adapta as telas aos seus temas, dados e identidade.',tags:['Conteúdo e pessoas','Pulse News','Pautas e recriações'],art:`<div class="mini-dashboard"><div><b>Seu painel</b><span>PRÉVIA</span></div><div class="mini-metrics"><i></i><i></i><i></i></div><svg viewBox="0 0 300 65" preserveAspectRatio="none" aria-hidden="true"><path d="M0 56 30 41 60 51 90 30 120 39 150 13 180 30 210 17 240 32 270 9 300 15" fill="none" stroke="#297e8d" stroke-width="2.5" stroke-linejoin="round"/></svg></div>`},review:{title:'Pronto para a sua revisão.',text:'Você confere os dados e a navegação antes de definir o acesso e as atualizações.',tags:['Validar','Ajustar','Evoluir'],art:`<div class="review-preview"><div>${icon('check')}Dados e fontes<span>conferir</span></div><div>${icon('check')}Identidade e temas<span>revisar</span></div><div>${icon('check')}Navegação e acesso<span>validar</span></div></div>`}};
  const buildTabs=[...document.querySelectorAll('[data-build]')];function activateBuild(tab){buildTabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1;});const stage=stages[tab.dataset.build];document.getElementById('build-title').textContent=stage.title;document.getElementById('build-description').textContent=stage.text;document.getElementById('build-art').innerHTML=stage.art;document.getElementById('build-tags').replaceChildren(...stage.tags.map(text=>{const span=document.createElement('span');span.textContent=text;return span;}));document.getElementById('build-counter').textContent='ETAPA 0'+(buildTabs.indexOf(tab)+1)+' / 04';document.getElementById('build-panel').setAttribute('aria-labelledby',tab.id);}wireTabs(buildTabs,activateBuild);activateBuild(buildTabs[0]);
})();
