window.PRESENTATION_DRAFT = {
  "defaultName": "Pulse",
  "version": "1.0.0",
  "releaseUrl": "https://github.com/juliooandradee/pulse-skill/releases/tag/v1.0.0",
  "downloadUrl": "https://github.com/juliooandradee/pulse-skill/releases/download/v1.0.0/pulse-v1.0.0.zip",
  "promptTemplate": "Estou no ChatGPT Work. Leia a skill Pulse e confira se este ambiente permite instalar uma skill avulsa e trabalhar com arquivos e navegador. Se a interface oferecer a instalação, prepare somente Pulse; se não oferecer, use o pacote como referência nesta tarefa e informe que não houve instalação persistente.\n\nFonte: https://github.com/juliooandradee/pulse-skill/tree/v1.0.0/pulse\nVersão: Pulse 1.0.0, somente a pasta pulse.\n\nAntes de copiar, confira a origem, a revisão e o destino da instalação. Se já existir uma versão, preserve-a. Não execute scripts durante a instalação nem instale outras skills, plugins, conectores, hooks ou dependências. Valide SKILL.md, referências, código e manifesto ao concluir.\n\nDepois, use Pulse para preparar meu painel privado. Pergunte meu @ público, objetivo, período e identidade visual. Analise apenas o que estiver publicamente acessível: não vincule nem sincronize a conta do Instagram, não peça senha, cookies ou tokens. Se houver bloqueio ou dado ausente, informe a cobertura parcial. Não invente Insights privados.\n\nComece por uma amostra pequena e explique o consumo de uso/créditos antes de ampliar. Inclua conteúdos com capas, conversas variadas, participantes com foto pública quando disponível, notícias com fonte e imagem, pautas e recriações entre Reel e carrossel. Preserve o histórico e os checks de Proposta feita. Prepare primeiro o app local; combine comigo login do time, hospedagem e eventual rotina semanal. Não publique nem envie mensagens a terceiros.\n\nSe instalada, selecione @pulse. Não crie plugin para contornar indisponibilidade.",
  "prompts": {
    "codex": "Use $skill-installer para instalar somente a skill Pulse deste endereço.\n\nFonte: https://github.com/juliooandradee/pulse-skill/tree/v1.0.0/pulse\nVersão: Pulse 1.0.0, somente a pasta pulse.\n\nAntes de copiar, confira a origem, a revisão e o destino da instalação. Se já existir uma versão, preserve-a. Não execute scripts durante a instalação nem instale outras skills, plugins, conectores, hooks ou dependências. Valide SKILL.md, referências, código e manifesto ao concluir.\n\nDepois, use Pulse para preparar meu painel privado. Pergunte meu @ público, objetivo, período e identidade visual. Analise apenas o que estiver publicamente acessível: não vincule nem sincronize a conta do Instagram, não peça senha, cookies ou tokens. Se houver bloqueio ou dado ausente, informe a cobertura parcial. Não invente Insights privados.\n\nComece por uma amostra pequena e explique o consumo de uso/créditos antes de ampliar. Inclua conteúdos com capas, conversas variadas, participantes com foto pública quando disponível, notícias com fonte e imagem, pautas e recriações entre Reel e carrossel. Preserve o histórico e os checks de Proposta feita. Prepare primeiro o app local; combine comigo login do time, hospedagem e eventual rotina semanal. Não publique nem envie mensagens a terceiros.\n\nQuando estiver disponível, inicie com $pulse.",
    "claude": "Instale somente a skill Pulse na pasta .claude/skills/pulse deste projeto, após conferir os arquivos.\n\nFonte: https://github.com/juliooandradee/pulse-skill/tree/v1.0.0/pulse\nVersão: Pulse 1.0.0, somente a pasta pulse.\n\nAntes de copiar, confira a origem, a revisão e o destino da instalação. Se já existir uma versão, preserve-a. Não execute scripts durante a instalação nem instale outras skills, plugins, conectores, hooks ou dependências. Valide SKILL.md, referências, código e manifesto ao concluir.\n\nDepois, use Pulse para preparar meu painel privado. Pergunte meu @ público, objetivo, período e identidade visual. Analise apenas o que estiver publicamente acessível: não vincule nem sincronize a conta do Instagram, não peça senha, cookies ou tokens. Se houver bloqueio ou dado ausente, informe a cobertura parcial. Não invente Insights privados.\n\nComece por uma amostra pequena e explique o consumo de uso/créditos antes de ampliar. Inclua conteúdos com capas, conversas variadas, participantes com foto pública quando disponível, notícias com fonte e imagem, pautas e recriações entre Reel e carrossel. Preserve o histórico e os checks de Proposta feita. Prepare primeiro o app local; combine comigo login do time, hospedagem e eventual rotina semanal. Não publique nem envie mensagens a terceiros.\n\nQuando estiver disponível, inicie com /pulse.",
    "work": "Estou no ChatGPT Work. Leia a skill Pulse e confira se este ambiente permite instalar uma skill avulsa e trabalhar com arquivos e navegador. Se a interface oferecer a instalação, prepare somente Pulse; se não oferecer, use o pacote como referência nesta tarefa e informe que não houve instalação persistente.\n\nFonte: https://github.com/juliooandradee/pulse-skill/tree/v1.0.0/pulse\nVersão: Pulse 1.0.0, somente a pasta pulse.\n\nAntes de copiar, confira a origem, a revisão e o destino da instalação. Se já existir uma versão, preserve-a. Não execute scripts durante a instalação nem instale outras skills, plugins, conectores, hooks ou dependências. Valide SKILL.md, referências, código e manifesto ao concluir.\n\nDepois, use Pulse para preparar meu painel privado. Pergunte meu @ público, objetivo, período e identidade visual. Analise apenas o que estiver publicamente acessível: não vincule nem sincronize a conta do Instagram, não peça senha, cookies ou tokens. Se houver bloqueio ou dado ausente, informe a cobertura parcial. Não invente Insights privados.\n\nComece por uma amostra pequena e explique o consumo de uso/créditos antes de ampliar. Inclua conteúdos com capas, conversas variadas, participantes com foto pública quando disponível, notícias com fonte e imagem, pautas e recriações entre Reel e carrossel. Preserve o histórico e os checks de Proposta feita. Prepare primeiro o app local; combine comigo login do time, hospedagem e eventual rotina semanal. Não publique nem envie mensagens a terceiros.\n\nSe instalada, selecione @pulse. Não crie plugin para contornar indisponibilidade.",
    "chatgpt": "Quero começar meu Pulse no ChatGPT. Leia o pacote abaixo e faça o diagnóstico. Para montar o aplicativo, confira se tenho Work ou ferramentas de arquivos e código; se não, explique como continuar no Work, Codex ou Claude Code. Não diga que a skill foi instalada apenas porque anexei os arquivos.\n\nFonte: https://github.com/juliooandradee/pulse-skill/tree/v1.0.0/pulse\nVersão: Pulse 1.0.0, somente a pasta pulse.\n\nAntes de copiar, confira a origem, a revisão e o destino da instalação. Se já existir uma versão, preserve-a. Não execute scripts durante a instalação nem instale outras skills, plugins, conectores, hooks ou dependências. Valide SKILL.md, referências, código e manifesto ao concluir.\n\nDepois, use Pulse para preparar meu painel privado. Pergunte meu @ público, objetivo, período e identidade visual. Analise apenas o que estiver publicamente acessível: não vincule nem sincronize a conta do Instagram, não peça senha, cookies ou tokens. Se houver bloqueio ou dado ausente, informe a cobertura parcial. Não invente Insights privados.\n\nComece por uma amostra pequena e explique o consumo de uso/créditos antes de ampliar. Inclua conteúdos com capas, conversas variadas, participantes com foto pública quando disponível, notícias com fonte e imagem, pautas e recriações entre Reel e carrossel. Preserve o histórico e os checks de Proposta feita. Prepare primeiro o app local; combine comigo login do time, hospedagem e eventual rotina semanal. Não publique nem envie mensagens a terceiros."
  },
  "names": [
    {
      "name": "Pulse",
      "direction": "Seu histórico, suas conversas e as próximas pautas."
    }
  ]
};
