(() => {
 const $=id=>document.getElementById(id),cfg=window.PRESENTATION_DRAFT;
 const setTheme=theme=>{document.documentElement.dataset.theme=theme;$('demo-theme').textContent=theme==='dark'?'☀':'☾';$('demo-theme').setAttribute('aria-label',theme==='dark'?'Ativar modo claro':'Ativar modo escuro');try{localStorage.setItem('pulse-demo-theme',theme);}catch{}};
 let theme='dark';try{theme=localStorage.getItem('pulse-demo-theme')||theme;}catch{}setTheme(theme==='light'?'light':'dark');
 $('demo-theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
 const conversations=[{who:'Ana · exemplo',initial:'A',text:'Como você confere se a resposta da IA está correta?',post:'IA na prática',likes:28,replies:6},{who:'Bruno · exemplo',initial:'B',text:'Dá para mostrar esse processo em um passo a passo?',post:'Rotina de estudos',likes:18,replies:4},{who:'Carla · exemplo',initial:'C',text:'O que muda quando a ferramenta erra?',post:'Segurança e evidência',likes:34,replies:9}];
 function drawConversations(order){$('demo-conversations').innerHTML=[...conversations].sort((a,b)=>order==='likes'?b.likes-a.likes:0).map(x=>`<article class="release-card conversation-demo"><div class="person-label"><span class="demo-avatar">${x.initial}</span><span>${x.who}</span></div><h3>“${x.text}”</h3><small>${x.post}</small><div class="comment-counts"><span>♡ ${x.likes} curtidas</span><span>↳ ${x.replies} respostas</span></div></article>`).join('');}
 document.querySelectorAll('[data-conversation-order]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-conversation-order]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawConversations(b.dataset.conversationOrder);});drawConversations('varied');
 $('demo-people').innerHTML=conversations.map((x,i)=>`<article class="release-card"><div class="person-label"><span class="demo-avatar">${x.initial}</span><div><h3>${x.who}</h3><small>Participante da amostra fictícia</small></div></div><div class="people-stats"><div><b>${8-i*2}</b><span>posts diferentes</span></div><div><b>${12-i*3}</b><span>comentários</span></div></div><p>${['Pergunta como verificar resultados.','Pede exemplos aplicados à rotina.','Participa das discussões sobre limites.'][i]}</p></article>`).join('');
 const ideas=[{id:'demo-remake-1',kind:'REEL → CARROSSEL',title:'Um tutorial que vira um checklist.',angle:'Transformar a demonstração em cinco passos que a pessoa possa consultar.',image:'DdHyK0DlNbu.jpg',origin:'Recriação do histórico'},{id:'demo-remake-2',kind:'CARROSSEL → REEL',title:'Uma conversa que merece um vídeo.',angle:'Retomar a pergunta central com um exemplo narrado e uma conclusão prática.',image:'DdKii02FHEQ.jpg',origin:'Recriação do histórico'},{id:'demo-news-1',kind:'NOTÍCIA → PAUTA',title:'O que o estudo realmente mostrou?',angle:'Separar o resultado, as limitações e o que ainda falta testar na prática.',image:'news-physician.jpg',origin:'Ideia a partir de uma fonte'}];
 let checks=new Set(),filter='all';try{checks=new Set(JSON.parse(localStorage.getItem('pulse-demo-checks')||'[]'));}catch{}
 function drawIdeas(){const visible=ideas.filter(x=>filter==='all'||(filter==='done')===checks.has(x.id));$('demo-proposals').innerHTML=visible.length?visible.map(x=>`<article class="release-card proposal-demo ${checks.has(x.id)?'proposal-done':''}"><img src="assets/${x.image}" alt="Imagem de referência para a proposta ilustrativa" loading="lazy"><div><small>${x.kind}</small><h3>${x.title}</h3><p>${x.angle}</p><span class="demo-note">${x.origin}</span><button type="button" class="proposal-check" data-demo-check="${x.id}" aria-pressed="${checks.has(x.id)}">${checks.has(x.id)?'✓ Proposta feita · desfazer':'□ Marcar proposta feita'}</button></div></article>`).join(''):'<p class="empty-state">Nenhuma proposta neste filtro. Marque uma ideia para experimentar.</p>';
 $('demo-proposals').querySelectorAll('[data-demo-check]').forEach(b=>b.onclick=()=>{const id=b.dataset.demoCheck;checks.has(id)?checks.delete(id):checks.add(id);try{localStorage.setItem('pulse-demo-checks',JSON.stringify([...checks]));$('demo-check-status').textContent='Check salvo neste navegador. Atualizar as pautas não apaga as propostas feitas.';}catch{$('demo-check-status').textContent='O navegador bloqueou o salvamento. O check vale apenas nesta visita.';}drawIdeas();});}
 document.querySelectorAll('[data-proposal-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.proposalFilter;document.querySelectorAll('[data-proposal-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));drawIdeas();});drawIdeas();
 const news=[{title:'IA na interpretação de exames',source:'npj Digital Medicine',url:'https://www.nature.com/npjdigitalmed/',image:'news-ecg.jpg',credit:'Jair Lázaro · Unsplash',creditUrl:'https://unsplash.com/photos/medical-monitor-displaying-vital-signs-0lrJo37r6Nk',text:'Um ângulo para explorar: onde o modelo acerta e o que ainda precisa de revisão.'},{title:'Agentes de IA na rotina médica',source:'Nature Medicine',url:'https://www.nature.com/nm/',image:'news-physician.jpg',credit:'Vitaly Gariev · Unsplash',creditUrl:'https://unsplash.com/photos/egCFrNJ6Djw',text:'Um ângulo para explorar: da simulação de pesquisa ao uso real no consultório.'},{title:'Evidência antes da novidade',source:'NEJM AI',url:'https://ai.nejm.org/',image:'news-patient.jpg',credit:'Vitaly Gariev · Unsplash',creditUrl:'https://unsplash.com/photos/GBcLdqOBbXE',text:'Um ângulo para explorar: o que foi medido, em quem e com quais limitações.'}];
 $('demo-news').innerHTML=news.map(x=>`<article class="release-card news-demo"><figure><img src="assets/${x.image}" alt="Foto contextual de ambiente médico; exemplo ilustrativo" loading="lazy"><figcaption>Foto ilustrativa · <a href="${x.creditUrl}" target="_blank" rel="noopener noreferrer">${x.credit}</a></figcaption></figure><div><small>EXEMPLO DE TEMA · ${x.source}</small><h3>${x.title}</h3><p>${x.text}</p><a class="text-link" href="${x.url}" target="_blank" rel="noopener noreferrer">Conhecer a fonte ↗</a></div></article>`).join('');
 $('demo-team-form').onsubmit=e=>{e.preventDefault();$('demo-team-status').textContent='Simulação: um membro teria permissão de visualização. Nenhum acesso foi criado.';$('demo-team-email').value='';};
 function updatePrompt(){const platform=$('install-platform').value;$('build-prompt').value=cfg.prompts[platform];$('copy-feedback').textContent='';document.querySelectorAll('[data-choose-platform]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.choosePlatform===platform)));}
 $('install-platform').onchange=updatePrompt;document.querySelectorAll('[data-choose-platform]').forEach(b=>b.onclick=()=>{$('install-platform').value=b.dataset.choosePlatform;updatePrompt();$('prompt').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});$('install-platform').focus({preventScroll:true});});updatePrompt();
 document.querySelectorAll('[data-release-link]').forEach(a=>a.href=cfg.releaseUrl);
 document.querySelectorAll('[data-download-link]').forEach(a=>a.href=cfg.downloadUrl);
})();
